{{- /* Combined .env template for CP Identity */ -}}
{{- with secret "database/creds/cp_identity_runtime" -}}
CP_IDT_DB_POSTGRES_URL=postgresql://{{ .Data.username }}:{{ .Data.password }}@${SUITE_DB_POSTGRES_HOST}:${SUITE_DB_POSTGRES_PORT}/identity_db
{{- end }}

{{ with secret "kv/data/cp/identity" -}}
CP_IDT_AUTH_SUPERTOKENS_API_KEY={{ .Data.data.supertokens_api_key }}
CP_IDT_AUTH_JWT_SECRET={{ .Data.data.jwt_secret }}
CP_IDT_AUTH_OIDC_CLIENT_SECRET={{ .Data.data.oidc_client_secret }}
{{- end }}

# Non-secret configuration propagated from env files
CP_IDT_APP_PORT=${CP_IDT_APP_PORT}
CP_IDT_APP_METRICS_PORT=${CP_IDT_APP_METRICS_PORT}
CP_IDT_APP_NODE_ENV=${CP_IDT_APP_NODE_ENV}
CP_IDT_AUTH_SUPERTOKENS_CONNECTION_URI=${CP_IDT_AUTH_SUPERTOKENS_CONNECTION_URI}
CP_IDT_AUTH_OIDC_ISSUER_URL=${CP_IDT_AUTH_OIDC_ISSUER_URL}
CP_IDT_AUTH_OIDC_CLIENT_ID=${CP_IDT_AUTH_OIDC_CLIENT_ID}
CP_IDT_AUTH_OIDC_REDIRECT_URIS=${CP_IDT_AUTH_OIDC_REDIRECT_URIS}
CP_IDT_AUTH_OIDC_LOGOUT_REDIRECT_URIS=${CP_IDT_AUTH_OIDC_LOGOUT_REDIRECT_URIS}
CP_IDT_OBS_OTEL_ENDPOINT=${CP_IDT_OBS_OTEL_ENDPOINT}
CP_IDT_OBS_SERVICE_NAME=${CP_IDT_OBS_SERVICE_NAME}
CP_IDT_OBS_METRICS_PORT=${CP_IDT_OBS_METRICS_PORT}
SUITE_OBS_OTEL_COLLECTOR_GRPC_URL=${SUITE_OBS_OTEL_COLLECTOR_GRPC_URL}
LOG_LEVEL=${LOG_LEVEL:-info}
NODE_ENV=production
