services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ../../otel-config/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - observability
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ../../dashboards/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ../../dashboards/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - observability
    ports:
      - 3000:3000

  loki:
    image: grafana/loki:latest
    networks:
      - observability
    volumes:
      - loki_data:/loki
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../../logs/ingestion/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - observability

networks:
  observability:
    name: geniuserp_observability
    driver: bridge

volumes:
  loki_data: