version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ../../otel-config/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - observability
    ports:
      - "9090:9090"

networks:
  observability:
    name: geniuserp_observability
    driver: bridge