{{- /* Combined .env template for CP Suite Shell */ -}}
{{- with secret "kv/data/cp/suite-shell" -}}
CP_SHELL_DB_POSTGRES_URL={{ .Data.data.db_url }}
CP_SHELL_AUTH_JWT_SECRET={{ .Data.data.jwt_secret }}
{{- end }}

# Non-secret configuration
CP_SHELL_APP_PORT=${CP_SHELL_APP_PORT}
CP_SHELL_APP_METRICS_PORT=${CP_SHELL_APP_METRICS_PORT}
CP_SHELL_APP_NODE_ENV=${CP_SHELL_APP_NODE_ENV}
CP_SHELL_AUTH_IDENTITY_URL=${CP_SHELL_AUTH_IDENTITY_URL}
CP_SHELL_EXEC_TIMEOUT_SECONDS=${CP_SHELL_EXEC_TIMEOUT_SECONDS}
CP_SHELL_WORKING_DIR=${CP_SHELL_WORKING_DIR}
CP_SHELL_API_SANDBOX_ENABLED=${CP_SHELL_API_SANDBOX_ENABLED}
CP_SHELL_OBS_OTEL_ENDPOINT=${CP_SHELL_OBS_OTEL_ENDPOINT}
CP_SHELL_OBS_SERVICE_NAME=${CP_SHELL_OBS_SERVICE_NAME}
CP_SHELL_OBS_METRICS_PORT=${CP_SHELL_OBS_METRICS_PORT}
SUITE_OBS_OTEL_COLLECTOR_GRPC_URL=${SUITE_OBS_OTEL_COLLECTOR_GRPC_URL}
LOG_LEVEL=${LOG_LEVEL:-info}
NODE_ENV=production
