{{- /* Combined .env template for CP Suite Admin */ -}}
{{- with secret "kv/data/cp/suite-admin" -}}
CP_ADMIN_DB_POSTGRES_URL={{ .Data.data.db_url }}
CP_ADMIN_AUTH_JWT_SECRET={{ .Data.data.jwt_secret }}
CP_ADMIN_API_AUDIT_WEBHOOK_URL={{ .Data.data.audit_webhook_url }}
{{- end }}

# Non-secret configuration
CP_ADMIN_APP_PORT=${CP_ADMIN_APP_PORT}
CP_ADMIN_APP_METRICS_PORT=${CP_ADMIN_APP_METRICS_PORT}
CP_ADMIN_APP_NODE_ENV=${CP_ADMIN_APP_NODE_ENV}
CP_ADMIN_AUTH_IDENTITY_URL=${CP_ADMIN_AUTH_IDENTITY_URL}
CP_ADMIN_AUTH_ADMIN_ROLES=${CP_ADMIN_AUTH_ADMIN_ROLES}
CP_ADMIN_LOG_LEVEL=${CP_ADMIN_LOG_LEVEL}
CP_ADMIN_OPERATION_TIMEOUT_SECONDS=${CP_ADMIN_OPERATION_TIMEOUT_SECONDS}
CP_ADMIN_OBS_OTEL_ENDPOINT=${CP_ADMIN_OBS_OTEL_ENDPOINT}
CP_ADMIN_OBS_SERVICE_NAME=${CP_ADMIN_OBS_SERVICE_NAME}
CP_ADMIN_OBS_METRICS_PORT=${CP_ADMIN_OBS_METRICS_PORT}
SUITE_OBS_OTEL_COLLECTOR_GRPC_URL=${SUITE_OBS_OTEL_COLLECTOR_GRPC_URL}
LOG_LEVEL=${LOG_LEVEL:-info}
NODE_ENV=production
