{{- /* Combined .env template for CP Analytics Hub */ -}}
{{- with secret "database/creds/cp_analytics_runtime" -}}
CP_ANLY_DB_POSTGRES_URL=postgresql://{{ .Data.username }}:{{ .Data.password }}@${SUITE_DB_POSTGRES_HOST}:${SUITE_DB_POSTGRES_PORT}/analytics_hub_db
{{- end }}

{{ with secret "kv/data/cp/analytics-hub" -}}
CP_ANLY_AUTH_JWT_SECRET={{ .Data.data.jwt_secret }}
CP_ANLY_DB_CLICKHOUSE_PASS={{ .Data.data.clickhouse_pass }}
CP_ANLY_DB_ELASTICSEARCH_PASS={{ .Data.data.elasticsearch_pass }}
CP_ANLY_API_MIXPANEL_KEY={{ .Data.data.mixpanel_key }}
CP_ANLY_API_GOOGLE_ANALYTICS_KEY={{ .Data.data.ga_key }}
CP_ANLY_API_HOTJAR_KEY={{ .Data.data.hotjar_key }}
{{- end }}

# Non-secret configuration
CP_ANLY_APP_PORT=${CP_ANLY_APP_PORT}
CP_ANLY_APP_METRICS_PORT=${CP_ANLY_APP_METRICS_PORT}
CP_ANLY_APP_NODE_ENV=${CP_ANLY_APP_NODE_ENV}
CP_ANLY_AUTH_IDENTITY_URL=${CP_ANLY_AUTH_IDENTITY_URL}
CP_ANLY_DB_CLICKHOUSE_URL=${CP_ANLY_DB_CLICKHOUSE_URL}
CP_ANLY_DB_CLICKHOUSE_USER=${CP_ANLY_DB_CLICKHOUSE_USER}
CP_ANLY_MQ_KAFKA_BROKERS=${CP_ANLY_MQ_KAFKA_BROKERS}
CP_ANLY_MQ_KAFKA_GROUP_ID=${CP_ANLY_MQ_KAFKA_GROUP_ID}
CP_ANLY_DB_ELASTICSEARCH_URL=${CP_ANLY_DB_ELASTICSEARCH_URL}
CP_ANLY_DB_ELASTICSEARCH_USER=${CP_ANLY_DB_ELASTICSEARCH_USER}
CP_ANLY_DB_REDIS_URL=${CP_ANLY_DB_REDIS_URL}
CP_ANLY_OBS_OTEL_ENDPOINT=${CP_ANLY_OBS_OTEL_ENDPOINT}
CP_ANLY_OBS_SERVICE_NAME=${CP_ANLY_OBS_SERVICE_NAME}
CP_ANLY_OBS_METRICS_PORT=${CP_ANLY_OBS_METRICS_PORT}
SUITE_OBS_OTEL_COLLECTOR_GRPC_URL=${SUITE_OBS_OTEL_COLLECTOR_GRPC_URL}
LOG_LEVEL=${LOG_LEVEL:-info}
NODE_ENV=production
