{{- /* Combined .env template for CP Suite Login */ -}}
{{- with secret "kv/data/cp/suite-login" -}}
CP_LOGIN_AUTH_JWT_SECRET={{ .Data.data.jwt_secret }}
{{- end }}

# Non-secret configuration injected from compose/.env
CP_LOGIN_APP_PORT=${CP_LOGIN_APP_PORT}
CP_LOGIN_APP_METRICS_PORT=${CP_LOGIN_APP_METRICS_PORT}
CP_LOGIN_APP_NODE_ENV=${CP_LOGIN_APP_NODE_ENV}
CP_LOGIN_AUTH_IDENTITY_URL=${CP_LOGIN_AUTH_IDENTITY_URL}
CP_LOGIN_REDIRECT_SUCCESS_URL=${CP_LOGIN_REDIRECT_SUCCESS_URL}
CP_LOGIN_REDIRECT_FAILURE_URL=${CP_LOGIN_REDIRECT_FAILURE_URL}
CP_LOGIN_SESSION_TIMEOUT_MINUTES=${CP_LOGIN_SESSION_TIMEOUT_MINUTES}
CP_LOGIN_OBS_OTEL_ENDPOINT=${CP_LOGIN_OBS_OTEL_ENDPOINT}
CP_LOGIN_OBS_SERVICE_NAME=${CP_LOGIN_OBS_SERVICE_NAME}
CP_LOGIN_OBS_METRICS_PORT=${CP_LOGIN_OBS_METRICS_PORT}
SUITE_OBS_OTEL_COLLECTOR_GRPC_URL=${SUITE_OBS_OTEL_COLLECTOR_GRPC_URL}
LOG_LEVEL=${LOG_LEVEL:-info}
NODE_ENV=production
